# Generated by Django 4.0.5 on 2022-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skilss_desdrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilss',
            name='yuz',
            field=models.CharField(default='', max_length=3),
        ),
    ]
