# Generated by Django 4.0.5 on 2022-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skilss_yuz'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='bolum',
            field=models.CharField(default='', max_length=200),
        ),
    ]
