# Generated by Django 4.0.5 on 2022-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_education_bolum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('descripson', models.TextField(max_length=500)),
                ('bolum', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
