# Generated by Django 4.0.5 on 2022-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projectdt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
