# Generated by Django 4.0.5 on 2022-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolio_category_portfolio_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='subname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
